---
# essential tasks. should run on all nodes
  - name: create devops user with admin privileges
    group: name=devops state=present

  - name: install htop package
    user: name=devops comment="Devops User" uid=2001 group=devops

  - name: install htop package
    action: yum name=htop state=present
